run <- function(...) {
  out("<!DOCTYPE html>")
  out("<head><title>SVG Test</title></head>")
  out("<body>")
  out("<svg height=\"300\" width=\"300\">")
  out("<g id=\"wrapper\"><circle id=\"svgcirc\" cx=\"50\" cy=\"50\" r=\"50\" fill=\"red\" onclick=\"updatePos();\" /></g>")
  out("</svg>")
  out("<script type=\"text/javascript\">")
  out("  var updatePos = function() {")
  out("      var el = document.getElementById(\"svgcirc\");")
  out("      var g = document.getElementById(\"wrapper\");")
  out("      if (window.XMLHttpRequest) {")
  out("          var insertCircle = function() {")
  out("              eval(httpr.responseText);")
  out("              console.log(e) // Lets just see what we're getting")
  out("              g.removeChild(el);")
  out("              g.appendChild(e);")
  out("          };")
  out("          httpr = new XMLHttpRequest();")
  out("          httpr.onreadystatechange = insertCircle;")
  out("          httpr.open('GET', \"circle?cx=\" + el.getAttribute(\"cx\"));")
  out("          httpr.send();")
  out("      }")
  out("  };")
  out("</script>")
  out("</body>")
  out("</html>")
  done()
}
