run <- function(...) {
  out("<!DOCTYPE html>")
  out("<head><title>SVG Test</title></head>")
  out("<body>")
  out("<svg height=\"300\" width=\"300\">")
  out("<g id=\"wrapper\"><circle id=\"svgcirc\" cx=\"50\" cy=\"50\" r=\"50\" fill=\"red\" onclick=\"updatePos();\" /></g>")
  out("</svg>")
  out("<script type=\"text/javascript\">")
  out("  var updatePos = function() {")
  out("      var el = document.getElementById(\"svgcirc\");")
  out("      var g = document.getElementById(\"wrapper\");")
  out("      if (window.XMLHttpRequest) {")
  out("          var insertCircle = function() {")
  out("              // Only execute the rest of the function when we have")
  out("              // received data from the server, not any intermediary states")
  out("              if (xhr.readyState !== 4)")
  out("                  return;")
  out("              var dp = new DOMParser();")
  out("              var newdoc = dp.parseFromString(xhr.responseText, \"image/svg+xml\");")
  out("              var newnode = document.importNode(newdoc.documentElement.firstChild, true);")
  out("              g.removeChild(el);")
  out("              g.appendChild(newnode);");
  out("          };")
  out("          xhr = new XMLHttpRequest();")
  out("          xhr.onreadystatechange = insertCircle;")
  out("          xhr.open('GET', \"circle?cx=\" + el.getAttribute(\"cx\"));")
  out("          xhr.send();")
  out("      }")
  out("  };")
  out("</script>")
  out("</body>")
  out("</html>")
  done()
}
