#+TITLE: FastRWeb example structure

The browser loads a page at the location
~http://localhost/cgi-bin/Rcgi/svgtest~

The page contains some SVG embedded within the HTML document, along
with a small amount of JavaScript.

The SVG circle contains an ~onclick~ handler that calls a JavaScript
function called ~updatePos~ each time it is clicked.

When updatePos is called, it sets up an AJAX request to call
~http://localhost/cgi-bin/Rcgi/circle~. However, the request includes
a single GET parameter, ~cx~, that is value of the ~cx~ attribute
present in the SVG circle that has the onclick event attribute.

As the AJAX request occurs, the code in circle.R is executed. What it
does is increment the value of ~cx~ by 30 and returns a JavaScript
string. When the browser receives the string, it is able to evaluate
it and build up an SVG element that is identical to the current
element, barring the incremented ~cx~ value.

We then swap out the old element with the new, so we have created a
method by which new SVG elements are created using R and establishing
communication between R and the browser.
